services:
  web-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blu-crawler
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/blu-crawler
      - logvolume01:/var/log
    depends_on:
      - redis
  jobs:
    build: .
    command: bin/jobs
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - redis
  redis:
    image: "redis:alpine"

volumes:
  logvolume01:
