services:
  web-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blu-crawler
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bundle exec rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/blu-crawler
