default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_user
  password: postgres_password
  host: datab
  port: 5432

development:
  <<: *default
  database: blu_crawler_api_development
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_user
  password: postgres_password
  host: datab

test:
  <<: *default
  database: blu_crawler_api_test

production:
  <<: *default
  database: blu_crawler_api_production
  username: blu_crawler_api
  password: <%= ENV["BLU_CRAWLER_API_DATABASE_PASSWORD"] %>
